name: Utilisation des Github Secrets

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    secret-api-call:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Show secret
              run: echo "My API KEY is ${{ secrets.API_KEY }}"