name: Utilisation des Github Secrets

on:
  push:
  workflow_dispatch:

jobs:
  send-discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit
        id: get_commit_message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Get first generated image
        id: get_image
        run: echo "IMAGE_NAME=$(ls ./images | head -n 1)" >> $GITHUB_ENV

      - name: Construct image URL
        id: construct_image_url
        run: echo "IMAGE_URL=https://hugo-potpot.github.io/ci-cd-test//images/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Send notification
        run: |
          curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -d '{
            "username": "Github Actions",
            "embeds": [
              {
                "title": "New commit",
                "description": "${{ env.message }}",
                "color": 8388736,
                "image": {
                  "url": "${{ env.IMAGE_URL }}"
                },
                "fields": [
                    {
                        "name": "Repository",
                        "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})"
                    },
                    {
                        "name": "Branch",
                        "value": "${{ github.ref }}"
                    }
                ],
                "footer": {
                  "text": "Github Actions - Automation"
                }
              }
            ]
          }'