name: Mon premier workflow

on:
  push:
    branches:
      - main

jobs:
  afficher-message:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher un message
        run: echo "Hello, world!"