name: Generate image from last commit

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit
        run: |
          last_commit=$(git log -1 --pretty=format:"%h %s")

      - name: Generate image
        run: |
          response=$(curl -d "{\"params\":[{\"name\":\"text1\",\"text\":\"$last_commit\",\"color\":\"#333\",\"backgroundColor\":\"#f9f9f9\",\"borderColor\":\"#ddd\",\"borderWidth\":\"1px\",\"borderRadius\":\"5px\",\"opacity\":1}]}" \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json" \
            -X POST https://api.dynapictures.com/designs/7f6476af6a)
          imageUrl=$(echo $response | jq -r '.imageUrl')
          timestamp=$(date +%Y%m%d%H%M%S)
          mkdir -p images
          curl -o images/image_$timestamp.png $imageUrl

      - name: Upload images as artifact
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: ./images/

  build-site:
    runs-on: ubuntu-latest
    needs: generate-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download images artifact
        uses: actions/download-artifact@v4
        with:
          name: images
          path: ./images/

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Generate HTML page
        run: python generate_html.py

      - name: Deploy to prod
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

  discord-notification:
    runs-on: ubuntu-latest
    needs: generate-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit
        id: get_commit_message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Download images artifact
        uses: actions/download-artifact@v4
        with:
          name: images

      - name: Get first generated image
        id: get_image
        run: |
          IMAGE_NAME=$(ls ./images)
          echo "image_name=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"

      - name: Construct image URL
        id: construct_image_url
        run: |
          echo "image_url=https://hugo-potpot.github.io/ci-cd-test/images/${{ steps.get_image.outputs.image_name }}" >> "$GITHUB_OUTPUT"

      - name: Send notification
        run: |
          echo "Message: ${{ env.message }}"
          echo "Image Name: ${{ steps.get_image.outputs.image_name }}"
          echo "Image URL: ${{ steps.construct_image_url.outputs.image_url }}"
          curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -d '{
            "username": "Github Actions",
            "embeds": [
              {
                "title": "New commit",
                "description": "${{ env.message }}",
                "color": 8388736,
                "image": {
                  "url": "${{ steps.construct_image_url.outputs.image_url }}"
                },
                "fields": [
                  {
                    "name": "Repository",
                    "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})"
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref }}"
                  }
                ],
                "footer": {
                  "text": "Github Actions - Automation"
                }
              }
            ]
          }'