name: Ajouter un commentaire sur la PR

on:
  pull_request:
      types: [opened, synchronize]


jobs:
    add-comment:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Get last commit
          run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

        - name: Add comment
          uses: actions/github-script@v6
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "Hello, I see you've just pushed a new commit. I will run some tests on it."
                })