name: Installer les outils

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nodeJS
        uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Install python
        uses: actions/setup-python@v5
        with:
            node-version: '3.13'

      - name: Check install
        run: |
          echo "Node version ${node -v}"
          echo "Python version ${python --version}" 
    
